name: Docker Image CI for GHCR

permissions:
  contents: read
  packages: write

on:
  push:
    paths:
      - 'Dockerfile'
  workflow_dispatch: # allows manual trigger

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u skprg --password-stdin

      - name: Build and Push Multi-Arch Docker Image
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64,linux/arm/v7 \
            --push \
            -t ghcr.io/skprg/hubzilla-docker:latest .

